{"abstract":[{"type":"text","text":"The endpoint encountered an unexpected internal error."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/internalError"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode","text":"HTTP2ErrorCode"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode"]]},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Type Property","externalID":"s:8NIOHTTP214HTTP2ErrorCodeV08internalC0ACvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","text":"HTTP2ErrorCode","kind":"typeIdentifier"}],"modules":[{"name":"NIOHTTP2"}],"role":"symbol","title":"internalError","symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/niohttp2\/http2errorcode\/internalerror"]}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode","abstract":[{"text":"An HTTP\/2 error code.","type":"text"}],"role":"symbol","title":"HTTP2ErrorCode","navigatorTitle":[{"kind":"identifier","text":"HTTP2ErrorCode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTP2ErrorCode"}],"type":"topic","url":"\/documentation\/niohttp2\/http2errorcode"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"url":"\/documentation\/niohttp2","kind":"symbol","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","title":"NIOHTTP2"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode/internalError":{"kind":"symbol","type":"topic","url":"\/documentation\/niohttp2\/http2errorcode\/internalerror","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/internalError","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","kind":"typeIdentifier","text":"HTTP2ErrorCode"}],"role":"symbol","abstract":[{"text":"The endpoint encountered an unexpected internal error.","type":"text"}],"title":"internalError"}}}